//! A curated wordlist for generating `word-word` identifiers. Sibling
//! module of `nickname`/`mesh` under `protocol`; `random_pair` backs
//! both `Nickname::random` and `MeshName::random`.

/// 1024 words — gives 1,048,576 possible two-word combinations.
pub(super) const WORDS: &[&str] = &[
    "abyss", "acre", "adrift", "agate", "agave", "alder", "alloy", "alpine", "amber", "anchor",
    "anvil", "apple", "arch", "arctic", "arrow", "aspen", "atlas", "attic", "aurora", "autumn",
    "avian", "axle", "azure", "badge", "balm", "bamboo", "barge", "bark", "barn", "basalt",
    "basin", "bay", "beacon", "beam", "bear", "beech", "bell", "bend", "berry", "birch", "blade",
    "blank", "blaze", "bliss", "bloom", "bluff", "blur", "board", "bolt", "bone", "book", "booth",
    "border", "boulder", "bound", "brace", "branch", "brass", "brave", "breach", "breeze", "brick",
    "bridge", "brief", "bright", "brink", "brook", "brush", "buck", "buoy", "burrow", "cabin",
    "cairn", "calm", "camp", "canal", "candle", "canyon", "cape", "carbon", "cargo", "cask",
    "cast", "cave", "cedar", "chain", "chalk", "chamber", "chasm", "chase", "cherry", "chime",
    "chip", "chord", "chrome", "cipher", "circle", "clad", "clamp", "clash", "clasp", "clay",
    "clear", "cliff", "cloak", "clock", "close", "cloud", "clover", "coast", "cobalt", "coil",
    "coin", "cold", "comet", "cone", "copper", "coral", "cord", "core", "cork", "corner", "cosmos",
    "cove", "craft", "crane", "crater", "creek", "crest", "crisp", "cross", "crown", "crush",
    "crypt", "crystal", "cube", "curve", "cycle", "dale", "damp", "dark", "dart", "dash", "dawn",
    "daze", "deep", "delta", "den", "depth", "desert", "dew", "dial", "digit", "dim", "dock",
    "dome", "door", "draft", "drake", "drape", "draw", "drift", "drum", "dune", "dusk", "dust",
    "eagle", "earth", "east", "echo", "edge", "eight", "elm", "ember", "epoch", "equal", "era",
    "exact", "fable", "facet", "faint", "falcon", "fall", "fang", "far", "farm", "fawn", "feast",
    "felt", "fence", "fern", "ferry", "fiber", "field", "fig", "film", "fin", "fire", "firm",
    "fjord", "flag", "flame", "flare", "flash", "flask", "flat", "fleet", "flight", "flint",
    "float", "flock", "flood", "floor", "flora", "flow", "flute", "foam", "fog", "foil", "fold",
    "font", "ford", "forge", "fork", "form", "fort", "fossil", "frame", "free", "frost", "fruit",
    "fume", "fur", "gale", "gap", "garden", "garnet", "gate", "gauge", "gear", "gem", "ghost",
    "glade", "glass", "gleam", "glen", "glide", "globe", "glow", "glyph", "gold", "gorge", "grain",
    "grand", "granite", "grant", "graph", "grasp", "grass", "gravel", "green", "grid", "grip",
    "grove", "guard", "guide", "gulf", "gust", "gypsum", "habit", "hail", "halo", "hammer", "hand",
    "harbor", "hare", "harp", "harvest", "hatch", "haven", "hawk", "haze", "heap", "heart",
    "heath", "hedge", "helm", "herb", "heron", "hide", "hill", "hinge", "hive", "hold", "hollow",
    "honey", "hood", "hook", "hope", "horizon", "horn", "hub", "hull", "hum", "hunt", "husk",
    "ibis", "icon", "igloo", "image", "inch", "index", "indigo", "inlet", "inner", "iron", "iris",
    "isle", "ivory", "ivy", "jackal", "jade", "jar", "jasper", "jet", "jewel", "joint", "journal",
    "joy", "jungle", "juniper", "keel", "keen", "keep", "kelp", "kernel", "kettle", "key",
    "kindle", "knack", "knob", "knoll", "knot", "label", "lace", "lake", "lamp", "lance", "land",
    "lantern", "larch", "lark", "latch", "lava", "lawn", "layer", "lead", "leaf", "lean", "ledge",
    "lemon", "lens", "level", "lever", "light", "lilac", "lime", "limit", "line", "linen", "link",
    "lion", "lock", "lodge", "loft", "log", "lone", "long", "loop", "lore", "lotus", "lumen",
    "lunar", "lure", "mace", "magnet", "mane", "manor", "maple", "marble", "march", "margin",
    "mark", "marsh", "mask", "mason", "mast", "match", "meadow", "mesa", "mesh", "metal", "mica",
    "mill", "mince", "mint", "mirror", "mist", "moat", "mold", "moon", "moor", "mortar", "moss",
    "moth", "mount", "mulch", "mural", "murmur", "muse", "myth", "nacre", "nail", "narrow", "nave",
    "near", "nebula", "needle", "nerve", "nest", "nexus", "niche", "night", "nimble", "nine",
    "node", "none", "nook", "north", "notch", "note", "novel", "null", "oak", "oar", "oasis",
    "ocean", "ochre", "olive", "omega", "onyx", "opal", "orbit", "orchid", "origin", "osprey",
    "otter", "outer", "oval", "oven", "oxide", "pact", "paddle", "page", "pail", "paint", "palm",
    "pane", "panel", "paper", "parch", "park", "parlor", "pass", "paste", "patch", "path",
    "patrol", "pause", "pave", "pawn", "peak", "pearl", "pebble", "pedal", "pellet", "petal",
    "phase", "pier", "pilot", "pine", "pipe", "pitch", "pixel", "place", "plain", "plan", "plank",
    "plant", "plate", "plaza", "pleat", "plumb", "plume", "plum", "pocket", "point", "poise",
    "polar", "pond", "pool", "poplar", "porch", "port", "post", "pouch", "power", "press", "pride",
    "prime", "print", "prism", "prize", "probe", "proof", "prose", "prune", "pulse", "pump",
    "pyrite", "quail", "quake", "quarry", "quartz", "quest", "quill", "quilt", "quota", "rack",
    "radar", "raft", "rail", "rain", "ramp", "ranch", "range", "rapid", "ratio", "raven", "reach",
    "realm", "reed", "reef", "reign", "relay", "relic", "ridge", "rift", "rim", "ring", "ripple",
    "rise", "river", "road", "roam", "roan", "robin", "rock", "rod", "rogue", "roof", "rook",
    "root", "rope", "round", "route", "ruin", "rune", "rush", "rust", "sable", "saddle", "safe",
    "sage", "sail", "salt", "sand", "satin", "scale", "scene", "scope", "scout", "seal", "seed",
    "shade", "shaft", "shard", "shell", "shield", "shift", "shore", "shrub", "siege", "signal",
    "silk", "silver", "simple", "siren", "skate", "slate", "sleep", "slice", "slide", "slope",
    "smart", "smith", "smoke", "snare", "snow", "socket", "solar", "solid", "sonic", "south",
    "space", "span", "spark", "spear", "sphere", "spice", "spike", "spine", "spiral", "spire",
    "spoke", "spore", "spray", "spring", "spruce", "spur", "swarm", "stack", "staff", "stage",
    "stair", "stake", "stale", "stalk", "stand", "star", "steam", "steel", "steep", "stem", "step",
    "stern", "still", "stock", "stone", "stoop", "storm", "stove", "strait", "strand", "straw",
    "stream", "stride", "strip", "stump", "style", "sugar", "suite", "summit", "surge", "swamp",
    "swarm", "sweep", "swift", "symbol", "table", "tack", "tale", "talon", "tangle", "taper",
    "tarn", "tarp", "teal", "tempo", "tent", "terra", "thatch", "thaw", "thorn", "thread",
    "throne", "thyme", "tide", "tile", "timber", "tint", "token", "toll", "tomb", "tone", "tool",
    "tooth", "torch", "tower", "trace", "track", "trade", "trail", "train", "trait", "tram",
    "trap", "tread", "treat", "trench", "trend", "tress", "trial", "tribe", "trick", "trim",
    "triple", "trove", "truce", "trunk", "trust", "tulip", "tundra", "tunnel", "turf", "twig",
    "twist", "ultra", "union", "unity", "upper", "urban", "umber", "vale", "valley", "valve",
    "vapor", "vault", "veil", "velvet", "venture", "verge", "verse", "vessel", "vigor", "vine",
    "vinyl", "violet", "vista", "vivid", "void", "volt", "voyage", "wade", "wager", "wagon",
    "wake", "walnut", "wand", "ward", "warm", "watch", "water", "wave", "wax", "weave", "wedge",
    "well", "west", "wheat", "wheel", "whirl", "wick", "wild", "willow", "wind", "wing", "winter",
    "wire", "wisp", "wolf", "wood", "wool", "wren", "yacht", "yard", "yarn", "year", "yew",
    "yield", "zenith", "zinc", "zone", "absorb", "accent", "adapt", "aerial", "almond", "amble",
    "amulet", "angle", "antler", "apex", "arbor", "array", "ash", "aspect", "audit", "awning",
    "axis", "ballad", "band", "banner", "barrel", "basis", "batch", "baton", "bench", "blend",
    "blind", "block", "bonus", "braid", "brand", "brew", "broad", "bronze", "broom", "brunt",
    "buffer", "bulb", "bundle", "burst", "butter", "cable", "cadence", "camo", "canopy", "caper",
    "carve", "catch", "causal", "cellar", "census", "chant", "charge", "chart", "chief", "cinder",
    "civic", "clam", "clause", "clerk", "climb", "clip", "clutch", "cobble", "codec", "commit",
    "common", "comply", "convex", "couple", "court", "cover", "cradle", "crate", "crawl", "credit",
    "crew", "crude", "cumin", "cupola", "curb", "custom", "dagger", "dairy", "dapper", "datum",
    "dealer", "decal", "decoy", "defer", "dense", "depot", "detour", "device", "dimple", "direct",
    "ditch", "divide", "dorsal", "double", "dowel", "dozen", "drench", "drill", "drip", "drove",
    "dry", "durable", "dwarf", "easel", "eaves", "eddy", "effort", "eighth", "elbow", "elder",
    "embark", "emblem", "emerge", "emit", "empire", "enamel", "endure", "engine", "engulf",
    "envoy", "erode", "escape", "estate", "ethic", "evade", "event", "evolve", "exceed", "exempt",
    "exile", "expand", "expert", "export", "extent", "fabric", "facile", "factor", "famine",
    "fathom", "favor", "feather", "fennel", "ferret", "fickle", "filter", "final", "fiscal",
    "flagon", "flannel", "flavor", "flicker", "florid", "fluent", "fodder", "follow", "fondle",
    "forbid", "formal", "fractal", "frantic", "frigate", "fringe", "frozen", "funnel", "furrow",
    "fusion", "gadget", "galley", "gambit", "garble", "garlic", "gauntlet", "gentle", "gibbon",
    "girder", "glacial", "goblet", "gothic", "grader", "graft", "grimace", "grotto", "growth",
    "grudge", "grunge", "gullet", "gunnel", "gutter", "halcyon", "hamlet", "handle", "hangar",
    "harness", "hasty", "hearth", "helix", "hermit", "hexagon", "hoist", "homage", "huddle",
    "humble", "hybrid", "ignite", "impel", "import", "invoke", "island", "nimbus", "parcel",
    "pilgrim", "plover", "quiver", "raptor", "sentry",
];

const _: () = assert!(!WORDS.is_empty());

/// A random `word-word` pair from the curated list.
///
/// The list is non-empty lowercase ASCII, so the result is always a
/// valid `Nickname`/`MeshName` (both bounded at 32 chars; the longest
/// pair here fits).
pub(super) fn random_pair() -> String {
    use rand::seq::IndexedRandom;
    let mut rng = rand::rng();
    let first = WORDS.choose(&mut rng).expect("wordlist is non-empty");
    let second = WORDS.choose(&mut rng).expect("wordlist is non-empty");
    format!("{first}-{second}")
}
