/**
 * Content-addressed serving for the built `.wasm`. Adapted from the
 * chat-webrtc example's `web/scripts/wasm-asset.ts` — same shape.
 *
 * The binary is served at `/wasm/light_cycles_web_bg.<hash>.wasm`, never at
 * a stable name. Two failures this exists to prevent, both of which read
 * as a bug in the Rust and are not:
 *
 * 1. A stale binary answering from cache after a rebuild. The symptom is a
 *    decode error on something the current source handles fine.
 * 2. A catch-all route serving `index.html` for a wasm URL that no longer
 *    exists, so the runtime reports
 *    `expected magic word 00 61 73 6d, found 3c 21 64 6f` — that is `<!do`.
 *    The `/wasm/` prefix outranks the catch-all precisely so a miss can
 *    404 honestly instead of returning a web page with a `.wasm`
 *    extension.
 */

const WASM_SOURCE = `${import.meta.dir}/../wasm/dist/light_cycles_web_bg.wasm`
const GENERATED_PATH = `${import.meta.dir}/../src/wasm-path.ts`

/** URL prefix. A real route, so a miss is a 404 rather than the SPA fallback. */
export const WASM_DIR = '/wasm'

export type WasmAsset = {
  /** `light_cycles_web_bg.<hash>.wasm` */
  name: string
  /** `/wasm/light_cycles_web_bg.<hash>.wasm` */
  path: string
  bytes: Uint8Array
}

export async function wasmAsset(): Promise<WasmAsset> {
  const file = Bun.file(WASM_SOURCE)
  if (!(await file.exists())) {
    throw new Error(
      `no wasm at ${WASM_SOURCE}\n` +
        'run ../build-wasm.sh first — the web app is a view onto a Rust build, not a build of its own',
    )
  }
  const bytes = new Uint8Array(await file.arrayBuffer())
  // 12 hex is 48 bits: far past collision territory for a file that changes a
  // few times an hour, and short enough to read in a network panel.
  const hash = new Bun.CryptoHasher('sha256').update(bytes).digest('hex').slice(0, 12)
  const name = `light_cycles_web_bg.${hash}.wasm`
  return { name, path: `${WASM_DIR}/${name}`, bytes }
}

/**
 * Regenerate `src/wasm-path.ts` so the client imports the current hash.
 *
 * Only writes when the contents change: an unconditional write would
 * retrigger the file watcher that called it, and the dev server would
 * rebuild forever.
 */
export async function writeWasmPath(asset: WasmAsset): Promise<void> {
  const contents =
    '// Generated by scripts/wasm-asset.ts. Do not edit; it is gitignored.\n' +
    `export const WASM_PATH = '${asset.path}'\n`
  const current = await Bun.file(GENERATED_PATH)
    .text()
    .catch(() => null)
  if (current !== contents) {
    await Bun.write(GENERATED_PATH, contents)
  }
}

export function wasmResponse(asset: WasmAsset): Response {
  return new Response(asset.bytes as BlobPart, {
    headers: {
      'content-type': 'application/wasm',
      // Safe forever precisely because the name carries the hash.
      'cache-control': 'public, max-age=31536000, immutable',
    },
  })
}
